### PR TITLE
Strict variables when logstash::configfile is used with $source parameter

### PR DESCRIPTION
**Pull request by sathieu**
Replaces #219

### CODE REVIEW

**Comment by sathieu** [comment]
I don't intend to signe a CLA for such a tiny patch. Consider it under public domain.

**Comment by sathieu** [comment]
ping?

**Comment by electrical** [comment]
Hi,

Without the CLA signed I'm unable to merge this..

**Comment by sathieu** [comment]
@electrical Oh please, this is a tiny patch. I release it under public domain.

**Comment by sathieu** [comment]
@electrical Patch updated and CLA signed.

**Comment by sathieu** [comment]
FYI this patch fails due to travis connectivity issues.

**Comment by jarpy** [comment]
I re-ran the tests, but now they are installing the wrong (the latest) Logstash version and thus failing, which suggests a bug in the tests.

I'm working on that now.

**Comment by jarpy** [comment]
Tests are fixed. Merging now.

Thank you for the patch, and your patience.

**Pull request merged**
