### PR TITLE
Add support for puppetlabs/apt 2.x

### PR DESCRIPTION
**Pull request by baurmatt**
This PR adds support for puppetlabs/apt 2.x and with this fixes deprecation warnings.

This PR also removes the anchor/stage usage for the logstash::repo class and moves the dependency management into logstash::repo itself. This is needed as other modules might also add apt repositories and require Class['apt::update']. When using the anchor/stage pattern this breaks as introduces a dependency cycle.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @baurmatt, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/puppet-logstash/pull/296.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by baurmatt** [comment]
I'm not sure anymore with which email i've signed the CLA last time. Probably one of my former employer. I've now signed the CLA again and added all email addresses i still have access to my Github profile.

**Comment by baurmatt** [comment]
Both failed tests aren't a result of this PR.

**Comment by baurmatt** [comment]
I've also removed the stage/anchor pattern as this introduces dependecy cycle if the logstash module is used with another module also using the apt class. See description of this PR for more information.

**Comment by jarpy** [comment]
Looks great! Thank you especially for re-aligning the tests.

I'm sorry for the spurious test failure from Puppet Enterprise on Debian.

**Pull request merged**
