### PR TITLE
Add systemd support for Debian 8

### PR DESCRIPTION
**Pull request by nerzhul**
Add a systemd unit file for Debian 8 and corresponding support

### CODE REVIEW

**Comment by nerzhul** [comment]
CLA is now signed

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
Thank you for the PR, just triggered a jenkins test.
At some point a lot will change on this module to be in line with how the ES puppet module looks like.

**Comment by nerzhul** [comment]
@electrical no problem, i just publish this PR to have my fix upstream and use upstream in production instead of our fork :)

**Comment by electrical** [comment]
@nerzhul makes sense :-) I think i will be able to merge this fairly soon and get it out there.
An updated LS puppet module from my side might take a bit of time because i'll be porting a lot of the changes from the ES puppet module into this one.

**Comment by jarpy** [comment]
Support for Debian 8 and systemd sneaked in through another patch. It is now tested and released.

Thank you for patch and inspiration however! :+1:

**Comment by karmi** [comment]
Hi @nerzhul, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/puppet-logstash/pull/246.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Pull request closed without merging**
