### PR TITLE
added gentoo support

### PR DESCRIPTION
**Pull request by derdanne**
- added gentoo support
- added possibility to specify package names for gentoo packages, because there are many overlays with different package names, and official package is missing
- modified package.pp to use package name from params.pp for installation
- added usage of openrc as default init for gentoo
- added initscript for gentoo clients

### CODE REVIEW

**Comment by electrical** [comment]
Hi,

I'm sorry i haven't processed this PR further, been very busy with LS 1.5 and the ES puppet module.
I'm now compiling a list of stuff to do for the LS puppet module and would like to include this PR as well.
There are some big changes coming up for which i'll be creating an issue of changes.
Are you still able to work on this further?

Thanks!

**Comment by derdanne** [comment]
Hi,

yes, i will work on this further. Just create the issues and i will do the changes that will be needed :)

**Comment by electrical** [comment]
Great thanks!

**Comment by electrical** [comment]
Can one of the admins verify this patch?

**Comment by breml** [comment]
@electrical & @derdanne This PR works beautifully for us. We would love to see this PR merged.

**Comment by mrcage** [comment]
This patch works well for. Could anyone merge this to the master branch?

**Comment by jarpy** [comment]
For Logstash 5.X, the module has been heavily rewritten. As a result, all outstanding pull requests (some of which are very old) are unfortunately suffering from severe merge conflicts, and many of them are probably no longer needed.

With the release of the new version, the time has come to close out all the pull requests that have, in all honesty, been neglected. Starting with a clean slate will help us focus on new pull requests that come in against the new code base and the much-improved acceptance test suite.

I apologise for the lost work that is represented in this pull request and will strive, as the current maintainer, to not let pull requests get into a state like this in future.

**Pull request closed without merging**
