### PR TITLE
Replace file_concat by puppetlabs-concat.

### PR DESCRIPTION
**Pull request by bzed**
Use puppetlabs-concat instead of the unknown file_concat module. Not well tested, but it should work :-)

### CODE REVIEW

**Comment by stack72** [comment]
@electrical this is a show stopper when people want to upgrade to puppet server and still use your module

**Comment by igalic** [comment]
+1 for puppet-server!

**Comment by cprice404** [comment]
I submitted a PR to file_concat which, if merged, I believe would alleviate the issue that people are seeing with Puppet Server.

**Comment by electrical** [comment]
Can one of the admins verify this patch?

**Comment by walterheck** [comment]
@bzed @electrical can you guys merge this PR? It means logstash and puppet 4 currently don't work:

```
[root@logstash ~]# puppet agent -t --environment _fix_filebeat_new
Info: Using configured environment '_fix_filebeat_new'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Notice: /File[/opt/puppetlabs/puppet/cache/lib/puppet/provider/file_concat]/ensure: created
Notice: /File[/opt/puppetlabs/puppet/cache/lib/puppet/provider/file_concat/ruby.rb]/ensure: defined content as '{md5}824274e592b32c0ca46d47caac2c7970'
Notice: /File[/opt/puppetlabs/puppet/cache/lib/puppet/type/file_concat.rb]/ensure: defined content as '{md5}51ce5cc0ee1f988036cb879cfb482fff'
Notice: /File[/opt/puppetlabs/puppet/cache/lib/puppet/type/file_fragment.rb]/ensure: defined content as '{md5}6f17af08284cbf235244b7a4b10bdb78'
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a '=>' expression, Could not autoload puppet/type/file_concat: uninitialized constant Puppet::Type::File::Owner at /etc/puppetlabs/code/environments/_fix_filebeat_new/modules/logstash/manifests/configfile.pp:45:5 at /etc/puppetlabs/code/environments/_fix_filebeat_new/site/profile/manifests/logstash.pp:21 on node logstash.olindata.vm
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
````

**Comment by walterheck** [comment]
The relevant PuppetLabs issue is here: https://tickets.puppetlabs.com/browse/SERVER-40

**Comment by caskolkm** [comment]
+ 1, can this be merged?

**Comment by cdenneen** [comment]
This can't be merged as it's not passing build. Also replacing ispavailability with electrical should be done to fix the current puppet server issue #193. I'm not sure where @electrical left off but he felt puppetlabs would be implementing his file_concat in their concat module. @tylerjl do you know history here with @puppetlabs? Is there open JIRA ticket to do this?

**Comment by igalic** [comment]
@cdenneen the current 2.1.x release of puppetlabs' concat should have all the functionality and speed that concat 1.x and file_concat had.

**Comment by walterheck** [comment]
@bzed can you sign the CLA and fix the build please? There's a bunch of people waiting for this..

**Comment by bzed** [comment]
@walterheck I've signed the cla, so feel free to take my patch, but as I'm not using the module anymore somebody else has to fix it I'm afraid.

**Comment by walterheck** [comment]
@bzed sorry, I don't actually work for elastic so I can't see whether or not you signed the CLA and in this case, why it is misrepresenting.
@electrical the Travis CI page says "The repository at elasticsearch/puppet-logstash was not found." can you see what's wrong?

**Comment by cdenneen** [comment]
It's elastic/puppet-logstash

**Comment by walterheck** [comment]
Oh right, fixed in #208 but the contributor might not have signed the CLA unless that's broken also.

**Comment by electrical** [comment]
@walterheck I left Elastic a while ago and someone else took it over. That said, Travis is not being used anymore. Just never removed the file :-(

**Comment by walterheck** [comment]
@electrical I got that idea, yeah. Can you ping "the new person" here by chance?

**Comment by cdenneen** [comment]
@tylerjl

**Comment by walterheck** [comment]
@tylerjl if you're the right person, this project _really_ needs some love and attention. If it is an option I'm happy to help maintain the elastic puppet modules. I don't want to end up forking if at all possible..

**Comment by tylerjl** [comment]
I hear you @walterheck, and I appreciate everyone's patience here. To be clear, I'm working hard at standardizing the CI setup across our modules so that there's no reason not to freely accept community PRs that get the green light from the tests.

**Comment by jarpy** [comment]
The recently released version of this module (v 0.6.0) seems to be happy when running under `puppetserver`.

I still plan to move to `puppetlabs-concat`, or remove the need for concat'ing altogether. I'll use this patch as a guide, but sadly, it's no longer a one-click merge, so I'll make the change the old-fashioned way. :(

**Pull request closed without merging**
