### PR TITLE
persist sort order of jvm.options and logstash.yml. Fixes #332

### LINKED ISSUE #332: Inconsistent sort order of hashes in jvm.options.erb and logstash.yml.erb
I'm having an issue on our production servers with the order of options in
template/jvm.options.erb and template/logstash.yml.erb

The servers run CentOS 6 with Ruby 1.8 and Puppet 3.8.7. Upgrading to Puppet 4 is no option (yet).

The order changes on every puppet run, causing a refresh of the logstash process.
Diff for last run:
```
--- /etc/logstash/logstash.yml	2017-03-20 12:13:46.528985209 +0100
+++ /tmp/puppet-file20170320-56750-odzb3q-0	2017-03-20 12:43:45.354662699 +0100
@@ -1,4 +1,4 @@
 --- 
-  path.config: /etc/logstash/conf.d
   path.data: /var/lib/logstash
+  path.config: /etc/logstash/conf.d
   path.logs: /var/log/logstash
```
The previous run:
```
-  path.logs: /var/log/logstash
-  path.data: /var/lib/logstash
   path.config: /etc/logstash/conf.d
+  path.data: /var/lib/logstash
+  path.logs: /var/log/logstash
```
..and so on and on and on and on.

The hash should be sorted, like `<% @jvm_options.sort.each do |line| -%>`.
This is already done in template/startup.options.erb, works fine there.

### PR DESCRIPTION
**Pull request by tkuther**

### CODE REVIEW

**Comment by jarpy** [comment]
Unfortunately, 8db8afe27c5c996bd60f98cf360f3b245dbe51c9 breaks the ability to specify options as a hierarchical data structure, as tested [here](https://github.com/elastic/puppet).

I suggest we shouldn't worry about Ruby 1.8. It's been [dead for 4 years](https://www.ruby-lang.org/en/news/2011/10/06/plans-for-1-8-7/), and all supported Puppet versions (4+) ship with Ruby 2.

**Comment by tkuther** [comment]
Thanks for testing! If it breaks features, then I do agree it should just be discarded.

We'll keep our local version pinned'n'patched until an upgrade to Puppet 4 is possible, no big deal.

Reading metadata.json Puppet 3.x is still supported. In combination wit CentOS/RedHat 6 even the default configuration causes unwanted behaviour, so Puppet 3.x should be dropped I guess.

**Comment by jarpy** [comment]
Thanks for being cool :)

**Comment by jarpy** [comment]
We're currently intending to completely drop Puppet 3 support with release 6 of the Elastic Stack and the Puppet modules. Until then, we're trying to keep things mostly working, but not at the cost of features or major clutter in the code.

Making the template output deterministic is still a worthy goal though, as long as we don't have to regress anything. Non-idempotent Puppet code drives me crazy too!

**Pull request closed without merging**
