### PR TITLE
add concat param to logstash to force creation of separate conf.d files

### PR DESCRIPTION
**Pull request by snobear**
Per #227, adds the `logstash::configfile::concat` param to optionally allow the config to be deployed as a separate file under conf.d.  Defaults to true, for backwards compat with existing behavior.

I think this will be a good path forward towards deprecating the combined `conf.d/logstash.conf` file.

### CODE REVIEW

**Comment by withnale** [comment]
Is this branch dead? Would really like to see this working to avoid the unnecessary concat dependency

**Comment by snobear** [comment]
@withnale let me fix the lint issue and make the build happy, and maybe we'll get some attention on this issue :).

**Comment by snobear** [comment]
Hi @electrical - can you comment on this issue when you get a chance?  Thanks.

**Comment by electrical** [comment]
Hi,

I think this PR has to much stuff that is unrelated to the actual addressed issue?
That said the concat stuff will go away eventually in the new release since its indeed not needed.

**Comment by snobear** [comment]
I removed some junk I had committed by accident.  Anyway, if you have plans to get rid of it anyway then I'll close this.

**Pull request closed without merging**
