### PR TITLE
Add package_install_opts to parameter

### LINKED ISSUE #199: Add package installation options parameter
The [current RPM](https://download.elasticsearch.org/logstash/logstash/packages/centos/logstash-1.4.2-1_2c0f5a1.noarch.rpm) requires jre >= 1.6.0 (OpenJDK). Using Oracle's JDK, without using OpenJDK, requires installing the RPM with the "--nodeps" option.

### PR DESCRIPTION
**Pull request by andy-s-clark**
Allows installing RPM package with the "--nodeps" option; closes #199.

### CODE REVIEW

**Comment by electrical** [comment]
Sorry for not reviewing this earlier.
I like it.
Could you sign the [CLA](http://www.elasticsearch.org/contributor-agreement/) so i can merge it?
Thanks!

**Comment by andy-s-clark** [comment]
I signed the CLA as Andrew Clark on 2015-01-16.

**Comment by electrical** [comment]
Can one of the admins verify this patch?

**Comment by jarpy** [comment]
For Logstash 5.X, the module has been heavily rewritten. As a result, all outstanding pull requests (some of which are very old) are unfortunately suffering from severe merge conflicts, and many of them are probably no longer needed.

With the release of the new version, the time has come to close out all the pull requests that have, in all honesty, been neglected. Starting with a clean slate will help us focus on new pull requests that come in against the new code base and the much-improved acceptance test suite.

I apologise for the lost work that is represented in this pull request and will strive, as the current maintainer, to not let pull requests get into a state like this in future.

**Pull request closed without merging**
