### PR TITLE
fix bug #228 when using ensure => absent more than once

### PR DESCRIPTION
**Pull request by exi**
This fixes ISSUE #228

### CODE REVIEW

**Comment by exi** [comment]
I signed he CLA after creating this pull request and don't know how to trigger the check again

**Comment by christofhaerens** [comment]
Hey exl, thxs for the fix. Implemented it until your pull request is merged.

**Comment by christofhaerens** [comment]
Seems my comment was a bit too early. Even with your fix in place still get the errors:

Error: Could not find init script for 'logstash'
Error: /Stage[main]/Logstash::Service/Logstash::Service::Init[logstash]/Service[logstash]/ensure: change from running to stopped failed: Could not find init script for 'logstash'
Notice: /Stage[main]/Logstash::Package/File[/var/lib/logstash/swdl]: Dependency Service[logstash] has failures: true
Warning: /Stage[main]/Logstash::Package/File[/var/lib/logstash/swdl]: Skipping because of failed dependencies
Notice: /Stage[main]/Logstash::Package/Logstash::Package::Install[logstash]/Package[logstash]: Dependency Service[logstash] has failures: true
Warning: /Stage[main]/Logstash::Package/Logstash::Package::Install[logstash]/Package[logstash]: Skipping because of failed dependencies
Notice: /Stage[main]/Logstash/Anchor[logstash::end]: Dependency Service[logstash] has failures: true
Warning: /Stage[main]/Logstash/Anchor[logstash::end]: Skipping because of failed dependencies


Tested it on sles 11, rhel 6 + 7 and all the same issue.

**Comment by exi** [comment]
@christofhaerens thanks for the feedback. sadly i don't think i will have time to have another look at this for some time so i would be happy if someone else might be able to address this.

**Comment by attachmentgenie** [comment]
works for me, please merge

**Comment by jarpy** [comment]
For Logstash 5.X, the module has been heavily rewritten. As a result, all outstanding pull requests (some of which are very old) are unfortunately suffering from severe merge conflicts, and many of them are probably no longer needed.

With the release of the new version, the time has come to close out all the pull requests that have, in all honesty, been neglected. Starting with a clean slate will help us focus on new pull requests that come in against the new code base and the much-improved acceptance test suite.

I apologise for the lost work that is represented in this pull request and will strive, as the current maintainer, to not let pull requests get into a state like this in future.

**Pull request closed without merging**
